main:
    server: 'http://server.com/software/tibco/packages'
    archive: 'archives'

dependencies: &dependencies
    - mq_cli: &mq_cli
        package: 'MQClient'
        config:
        action: 'install'

adapters: &adapters
    - obj: &obj

plugins: &plugins

libraries: &libraries
    - lib1: &lib1
        package: 'library_1'
    - lib2: &lib2
        package: 'library_2'

packages:
    - rv: &rv
        package: 'TIB_rv_8.4.3_linux_x86.zip'
        config: 'Install_TIB_rv_8.4.3_linux_x86.silent'
        action:
    - bw: &bw
        package: 'TIB_BW_6.2.1_linux26gl23_x86_64.zip'
        config: 'Install_TIB_BW_6.2.1_linux26gl23_x86_64.silent'
        action:
    - tra: &tra
        package: 'TIB_TRA_5.9.0_linux_x86_64.zip'
        config: '   Install_TIB_TRA_5.9.0_linux_x86_64.silent'
        libraries:
            - *lib1
            - *lib2
        action:
    - tea: &tea
        package: 'TIB_tea_2.1.0_linux26gl23_x86_64.zip'
        config: 'Install_TIB_tea_2.1.0_linux26gl23_x86_64.silent'
        plugins:
        action:
    - hawk: &hawk
        package: 'TIB_hawk_5.2.0_linux26gl23_x86_64.zip'
        config: 'Install_TIB_hawk_5.2.0_linux26gl23_x86_64.silent'
        action:
    - bpm: &bpm
        package: 'TIB_amx-bpm_3.1.0_linux24gl23_x86_64.zip'
        config: 'Install_TIB_amx-bpm_3.1.0_linux24gl23_x86_64.silent'
        action:
    - ems: &ems
        package: 'TIB_ems_8.2.1_linux_x86.zip'
        config: 'Install_TIB_ems_8.2.1_linux_x86.silent'
        action:
    - bpmadmin: &bpmadmin
        package:
        config:
        action:

set_admin:
    - *rv
    - *tea
    - *hawk

set_bpm:
    - *bpm

set_bw:
    - *rv
    - *tra
    - *bw
    - *adapters
    - *plugins

set_ems:
    - *ems

set_bpmadmin:
    - *bpmadmin
    - *hawk

